name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.mydomain.com:9087
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: harbor.mydomain.com:9087/sanjaypramod/nginx-website:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
