name: Build, Push, and Deploy
 
on:
  push:
    branches:
      - 
 
jobs:
  build-deploy:
    runs-on: self-hosted  # Use the self-hosted runner
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sanjaypramod
          password: sanjaypramod1234
 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sanjaypramod/nginx-website:latest
 
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  # Make sure the KUBECONFIG secret is added in GitHub
          chmod 600 $HOME/.kube/config  # Secure permissions
 
      - name: Deploy to K3s
        run: |
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: harbor.mydomain.com:9087/test/mynodeapp:v1  # Replace with your actual image name and tag
        ports:
        - containerPort: 3900
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 3900
    targetPort: 3900
          EOF
