name: Build, Tag, and Push to Harbor

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.mydomain.com:9087
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set Docker image version
        run: echo "IMAGE_VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

      #- name: Build Docker image
      #  run: docker build -t myapp:${{ env.IMAGE_VERSION }} .
        
      - name: Build Docker image
        run: docker build -t harbor.mydomain.com:9087/test/myapp:${{ env.IMAGE_VERSION }} .

      - name: Tag Docker image for Harbor
        run: docker tag myapp:${{ env.IMAGE_VERSION }} harbor.mydomain.com:9087/test/myapp:${{ env.IMAGE_VERSION }}

      - name: Push Docker image to Harbor
        run: docker push harbor.mydomain.com:9087/test/myapp:${{ env.IMAGE_VERSION }}
