name: Build, Push, and Deploy
 
on:
  push:
    branches:
      - 
 
jobs:
  build-deploy:
    runs-on: self-hosted  # Use the self-hosted runner
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sanjaypramod
          password: sanjaypramod1234
 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sanjaypramod/nginx-website:latest
 
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  # Make sure the KUBECONFIG secret is added in GitHub
          chmod 600 $HOME/.kube/config  # Secure permissions
 
      - name: Deploy to K3s
        run: |
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-website
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx-website
            template:
              metadata:
                labels:
                  app: nginx-website
              spec:
                containers:
                  - name: nginx
                    image: sanjaypramod/nginx-website:latest
                    ports:
                      - containerPort: 80
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            selector:
              app: nginx-website
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: NodePort
          EOF
